"$schema": https://github.com/hyperledger-labs/fablo/releases/download/1.1.0/schema.json
global:
  fabricVersion: 2.4.3
  tls: true
hooks:
  postGenerate: perl -i -pe 's/_VERSION=2.4.3/_VERSION=2.5.1/g' ./fablo-target/fabric-docker/.env; perl -i -pe 's/FABRIC_CA_VERSION=1.5.0/FABRIC_CA_VERSION=1.5.6/g' ./fablo-target/fabric-docker/.env
orgs:
  - organization:
      name: Org1
      domain: org1.example.com
    peer:
      instances: 1
    orderers:
      - groupName: group1
        prefix: orderer
        type: solo
        instances: 1
  - organization:
      name: Aud1
      domain: aud1.example.com
    peer:
      instances: 1
channels:
  - name: mychannel
    orgs:
      - name: Org1
        peers:
          - peer0
      - name: Aud1
        peers:
          - peer0
chaincodes:
  - name: auti-local-chain
    version: 0.1.0
    lang: golang
    channel: mychannel
    endorsement: AND('Org1MSP.member', 'Aud1MSP.member')
    directory: "contract/clolc_local_chain"
